- type: job
  id: Angler
  name: Angler
  description: Fish love me. The crew fears me.
  playTimeTracker: JobAngler
  startingGear: AnglerGear
  canBeAntag: true
  icon: JobIconAngler
  setPreference: true
  access:
  - Hydroponics
  - Service
  - Maintenance
  extended:
  - Kitchen
  - Bar
  
- type: startingGear
  id: AnglerGear
  equipment:
    jumpsuit: ClothingUniformOveralls
    id: AnglerPDA
    back: ClothingBackpack
    head: ClothingHeadFishCap
    ears: ClothingHeadsetService
    shoes: ClothingShoesGaloshes
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - FishingRodBase
    
- type: entity
  parent: BasePDA
  id: AnglerPDA
  name: angler PDA
  description: A bit fishy...
  components:
  - type: Pda
    id: AnglerIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-hydro
  - type: PdaBorderColor
    borderColor: "#44843c"
    accentVColor: "#00cc35"
  - type: Icon
    state: pda-hydro

- type: entity
  parent: IDCardStandard
  id: AnglerIDCard
  name: angler ID card
  components:
  - type: Sprite
    sprite: _hereelabs/Objects/Misc/id_cards.rsi
    layers:
    - state: default
    - state: idangler
  - type: PresetIdCard
    job: Angler
    
- type: jobIcon
  parent: JobIcon
  id: JobIconAngler
  icon:
    sprite: /Textures/_hereelabs/Interface/Misc/job_icons.rsi
    state: Angler
  jobName: Angler