- type: job
  id: StaffAssistant
  name: "Staff Assistant"
  description: "'Assist' the crew. Weld every airlock you find. Eventually get arrested by security and thrown out an airlock."
  playTimeTracker: JobStaffAssistant
  startingGear: StaffAssistantGear
  icon: "JobIconStaffAssistant"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: jobIcon
  parent: JobIcon
  id: JobIconStaffAssistant
  icon:
    sprite: /Textures/_hereelabs/Interface/Misc/job_icons.rsi
    state: StaffAssistant
  jobName: StaffAssistant

- type: startingGear
  id: StaffAssistantGear # This entire loadout is bullshit. Good thing this is an admeme role
  equipment:
    id: StaffAssistantPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitStaffie
    shoes: ClothingShoesColorBlack
    gloves: ClothingHandsGlovesColorYellow
    belt: ClothingBeltUtilityEngineering
    eyes: ClothingEyesGlassesMeson
    mask: ClothingMaskGas
    back: ClothingBackpack
    
- type: entity
  parent: IDCardStandard
  id: StaffAssistantIDCard
  name: staff assistant ID card
  components:
  - type: Sprite
    sprite: _hereelabs/Objects/Misc/id_cards.rsi
    layers:
    - state: default
    - state: idassistant
  - type: PresetIdCard
    job: StaffAssistant
    
- type: entity
  parent: BasePDA
  id: StaffAssistantPDA
  name: staff assistant PDA
  description: Why isn't it gray?
  components:
  - type: Pda
    id: StaffAssistantIDCard
  - type: PdaBorderColor
    borderColor: "#717059"
    
- type: entity
  parent: [ClothingUniformBase, ClothingUniformFoldableBase]
  id: ClothingUniformJumpsuitStaffie
  name: staff assistant's jumpsuit
  description: Imported directly from NT13. Looks clean... but not much notable otherwise.
  components:
  - type: Sprite
    sprite: _hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi
  - type: Clothing
    sprite: _hereelabs/Clothing/Uniforms/Jumpsuit/staffie.rsi
    
- type: entity
  parent: [ClothingUniformBase]
  id: ClothingUniformJumpsuitStaffieAlt
  name: staff assistant's jumpsuit
  description: Imported directly from NT13. Looks tidy!
  components:
  - type: Sprite
    sprite: _hereelabs/Clothing/Uniforms/Jumpsuit/staffie2.rsi
  - type: Clothing
    sprite: _hereelabs/Clothing/Uniforms/Jumpsuit/staffie2.rsi