- type: job
  id: Rancher
  name: Rancher
  description: Farm animals love me. The crew is indifferent to me.
  playTimeTracker: JobRancher
  startingGear: RancherGear
  canBeAntag: true
  icon: JobIconRancher
  setPreference: true
  access:
  - Hydroponics
  - Service
  - Maintenance
  extended:
  - Kitchen
  - Bar
  
- type: startingGear
  id: RancherGear
  equipment:
    jumpsuit: ClothingUniformBrownSuit
    id: RancherPDA
    back: ClothingBackpackSatchelLeather
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatCowboyBrown
    ears: ClothingHeadsetService
    mask: ClothingMaskBandBrown
    shoes: ClothingShoesBootsCowboyBrown
    gloves: ClothingHandsGlovesColorLightBrown
    outerClothing: ClothingOuterCoatPufferDark
  storage:
    back:
    - WeaponRevolverInspector
    - SpeedLoaderMagnumStun
    - SpeedLoaderMagnumStun
    
- type: entity
  parent: BasePDA
  id: RancherPDA
  name: rancher PDA
  description: It's surprisingly clean for a Rancher's PDA.
  components:
  - type: Pda
    id: RancherIDCard
  - type: Appearance
    appearanceDataInit:
     enum.PdaVisuals.PdaType:
       !type:String
       pda-hydro
  - type: PdaBorderColor
    borderColor: "#44843c"
    accentVColor: "#00cc35"
  - type: Icon
    state: pda-hydro

- type: entity
  parent: IDCardStandard
  id: RancherIDCard
  name: rancher ID card
  components:
  - type: Sprite
    sprite: _hereelabs/Objects/Misc/id_cards.rsi
    layers:
    - state: default
    - state: idrancher
  - type: PresetIdCard
    job: Rancher
    
- type: jobIcon
  parent: JobIcon
  id: JobIconRancher
  icon:
    sprite: /Textures/_hereelabs/Interface/Misc/job_icons.rsi
    state: Rancher
  jobName: Rancher